### ISSUE TITLE
Difficulty Select for Quake 64

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#101]
Since Quake 64 doesn't have a starting map to select your difficulty, a difficulty menu will need to be implemented when starting a new game.

**Comment by andrei-drexler** [comment]
Good idea, added in 29293163193328f43e0ec688430c291cd59a7ec5.

**Comment by liPillON** [comment]
hi! sorry for posting in a closed issue, buut..
would be feasible to extend this feature to all mods/mapsets that do not provide their own start.bsp?
(i.e. Func Map Jams 1-4)

thank you and keep up the good work!

**Comment by andrei-drexler** [comment]
Unfortunately, I don't think that would help much. The skill menu is shown before loading start.bsp, but for mods that don't have their own start map the vanilla one gets loaded. You still need to use the console to load any of the custom maps, so you might as well also type `skill <N>` before that. What those mods really need is a level selection menu (in addition to a skill selection menu). which is on my todo list.
