### ISSUE TITLE
error linking cull/mark program. Out of resource error.

### ISSUE THREAD

**Issue by lukazumi** [andrei-drexler/ironwail#108]
Trying to run on Win10x64, with i5-5220u (intel hd5500), and receive this error. I have copied ID1 from my quake installation (GOG).
Any ideas what the cause of this error is?

**Comment by andrei-drexler** [comment]
It's a bug in the driver's shader compiler. I've added a work-around in commit https://github.com/andrei-drexler/ironwail/commit/1771e012d57c4975bf75acbe72169841c03859a0.

**Comment by andrey-budko** [comment]
@andrei-drexler, for some reason my Intel HD Graphics 4600 still does not like cull_mark_compute_shader.

Error compiling cull/mark compute shader : 
ERROR: 1:120: ')' : syntax error syntax error

The only way I was able to fix this is replacing SURF_FRAMECOUNT, SURF_TEXNUM, SURF_NUMEDGES and SURF_FIRSTVERT defines with its content.

https://pastebin.com/ib64LEpG

Now ironwail compiles and runs fine on that old hardware.

**Comment by andrei-drexler** [comment]
Thanks for letting me know, @andrey-budko. The strange part is that the GPU I tested this fix on is an HD Graphics 4400, and I would've expected a 4600 to share the same bugs... I'm wondering if the comments in the SIZEOF_CMD/SIZEOF_SURFACE macros are triggering this, though - could you please try the current code but without those comments? I'd really like to avoid making the shader any less readable than it already is, if possible.

**Comment by andrey-budko** [comment]
```
-"#define SIZEOF_CMD                                    5 // uints\n"
+"#define SIZEOF_CMD                                    5\n"

-"#define SIZEOF_SURFACE                                2 // uvec4s\n"
+"#define SIZEOF_SURFACE                                2\n"
```

same error, unfortunately

**Comment by andrei-drexler** [comment]
Ah, that's unfortunate, thanks for trying, though! Maybe replacing `uint(base)` with just `base` in the CMD_/SURF_* macros might do the trick?

**Comment by andrey-budko** [comment]
No, it does not. But looks like I found the solution. Removing 'u' suffix does help.

https://pastebin.com/YYtmdX7d

**Comment by andrei-drexler** [comment]
Great, thanks! Hopefully https://github.com/andrei-drexler/ironwail/commit/ba3a6dd2ae993e1b6dd49d913e0859210554f7b6 is the end of it.

**Comment by lukazumi** [comment]
Do you have an idea when this will be in a new release? Looking forward to trying this engine!

Tanks!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by andrei-drexler** [comment]
Probably in a few weeks, maybe a bit more, there are still some things I'd like to finish. I can make a build with the latest code if you want to test it, though.

**Comment by lukazumi** [comment]
I will wait for the next build, thanks for the offer though.

Thank you!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Mhbuur** [comment]
I'm having the same problem with 0.6.0 and a HD Graphics 4600. @andrei-drexler Is there a build available with this fix somewhere?

**Comment by garoto** [comment]
If you're not bothered to be around command lines, Ironwail (and Quakespasm) can be built somewhat effortlessly on any Windows machine with the help of w64devkit: https://github.com/skeeto/w64devkit/releases

Just unzip the 70MB `"w64devkit-1.18.0.zip"` somewhere, double-click the .exe named `w64devkit.exe` and a cmd.exe Window should pop-up with a Unix-like shell prompt.

Paste the following in the cmd.exe window for a much more useful and readable prompt: 

```
export PS1='\n\[\e[1;33m\][ \w ]\[\e[0;33m\]\n[$SHLVL]\[\e[0;32m\]\u\[\e[1;32m\]@\[\e[0;36m\]w64devkit:# \[\e[0m\]'
```

I've made a simple guide of sorts (it's just the sequence of commands) in HTML format: https://0x0.st/HrYX.html
