### ISSUE TITLE
CSQC forward compatibility

### ISSUE THREAD

**Issue by temx** [andrei-drexler/ironwail#113]
Not sure if this is still in progress, but when connecting to or playing back a demo recorded by any other client (or an older version of Ironwail) you get a broken (Alkaline) or outright missing (Arcane Dimensions) CSQC HUD unless you manually set `cl_nocsqc` to `1`.

**Comment by andrei-drexler** [comment]
Thanks, https://github.com/andrei-drexler/ironwail/commit/4327891d2b66f65a4e45ab2aed2dea3e6a77b49a should take care of that.
