### ISSUE TITLE
[Bug] Score Stats Aren't Updated in Alkaline and Arcane Dimensions

### ISSUE THREAD

**Issue by 4LT** [andrei-drexler/ironwail#115]
Monsters killed and secrets found aren't updated in the score stats in Arcane Dimensions and Alkaline.  Skill value does not reflect actual cvar value.

I found a fix for the kill count and secrets, but not the skill value:
https://github.com/4LT/ironwail/commit/341c14c846e05e9272147a399a4f101fd81b3828

Edit: I had that a little wrong on the skill value: it updates correctly in Alkaline, but not in Arcane Dimensions

**Comment by 4LT** [comment]
So AD uses something called `autocvar` which is defined as an intrinsic in FTEQCC (see doc): https://www.fteqcc.org/dl/fteqcc_manual.txt

Seems like a fix for that would be much more involved

**Comment by andrei-drexler** [comment]
Thanks, should be fixed by https://github.com/andrei-drexler/ironwail/commit/effea0a79453f30bc554ab08c816854b2a373345 and https://github.com/andrei-drexler/ironwail/commit/33cfe56ed79ff8d96cf6f01520c7318891f45b65.
