### ISSUE TITLE
Crash to console on launching jam8_newhouse

### ISSUE THREAD

**Issue by 4LT** [andrei-drexler/ironwail#116]
## Version
Latest build from master branch

## System Specs
Linux
x86_64

## Additional Info

Log dump:

```
map jam8_newhouse
ADDRESS    2829(part)entity 0   125(effects).effects 14633(?)             
     misc.qc : misc_spark_spawn
<NO FUNCTION>
assignment to world entity
Host_Error: Program error
Shutting down SDL sound
```

https://www.quaddicted.com/reviews/jam8_rezipped.html

Note that this release is packaged with Arcane Dimensions 1.42

This *does not* occur on QuakeSpasm 0.94.~~6~~7

**Comment by 4LT** [comment]
Seems there's a bug in that version of AD

https://github.com/SimsOCallaghan/ArcaneDimensions/blob/a5ec293318eb24dbd0667e18e2e40be290021dd7/misc.qc#L871

`part` should be `spark` here, and it seems that ironwail is detected as DarkPlaces

**Comment by andrei-drexler** [comment]
Added a work-around in https://github.com/andrei-drexler/ironwail/commit/522d346049240f89bb8a7c01df1ed7bf8011970e that makes AD consider the engine FTE-like instead of DP-like (avoiding that bug).
