### ISSUE TITLE
[BUG] +showscores  program error with  AD hud styles 6 and 7

### ISSUE THREAD

**Issue by j4reporting** [andrei-drexler/ironwail#118]
this is on current git master version.  Did not check which commit introduced this issue
+showscores  aborts/disconnects  game back to console   if AD hud style 6 or 7 is active

how to reproduce:
1. cycle with 'H' ( impulse 178 )  and select  hud style   6 or 7 
2. press TAB  ( + showscores )

![Ironwail_HUD_error](https://user-images.githubusercontent.com/45177907/183099348-b59aed8d-563f-42f3-8502-f227edc9f898.png)

**Comment by andrei-drexler** [comment]
Good catch, thanks! Fixed in https://github.com/andrei-drexler/ironwail/commit/198791ab3ecadad0c3b994d3df34c06681e6125b.
