### ISSUE TITLE
[Bug] Not all cvars are written to the config file

### ISSUE THREAD

**Issue by V0du** [andrei-drexler/ironwail#119]
I usually modify the v_gunkick, cl_rollangle and cl_bob cvars values but they don't get written to the config file.
I can add them to the file manually, but if I change some settings using the in-game options menu the config gets overwritten.
A writeconfig command would be very useful in my opinion.

**Comment by mhQuake** [comment]
That's what autoexec.cfg is for.

**Comment by andrei-drexler** [comment]
Not all cvars are meant to be saved to config, so *technically* this isn't a bug. For those cvars that aren't saved it's true that `autoexec.cfg` is the standard solution, but I don't think that's very user-friendly, so I've changed `cl_rollangle` and `cl_bob` to get saved in commit 2071db51751c74e397cbea35b6ae8c31ebfd2a03. A similar change was made to `v_gunkick` a while ago in commit bf3c1ac7f24fd32e770f399e9d6c997618691875. There are probably more cvars that should get the same treatment.

I've also added a `writeconfig` command in 05b2f3bf30097e5f551ac64d2521bc6c3e8ca09c - by default it'll write `ironwail.cfg`, but you can optionally specify a different file name. Note that this won't write all cvars, either, the file will contain exactly the same data that is saved automatically when closing the game.
