### ISSUE TITLE
[bug?]

### ISSUE THREAD

**Issue by timbergeron** [andrei-drexler/ironwail#120]
maps with quake special chars do not display properly in window title

![Capture](https://user-images.githubusercontent.com/68674590/183495508-b0739d52-8ad6-4c06-a6fd-4e20f61ddb90.JPG)

**Comment by andrei-drexler** [comment]
Fixed in https://github.com/andrei-drexler/ironwail/commit/a16b0759932d9cabf569c52057e2c62c2f26603b:

<img width="960" alt="ironwail_unicode_title" src="https://user-images.githubusercontent.com/5121829/183525125-658ad2f0-e69d-4014-bf30-e3b38e2e21ad.png">
