### ISSUE TITLE
[Feature request] Hide console when quick-loading

### ISSUE THREAD

**Issue by V0du** [andrei-drexler/ironwail#128]
Console is shown and closed when quick-loading.
Just a small adjustment to make quick-loading more fluid.

**Comment by andrei-drexler** [comment]
Implemented in a04e88f69c49277c83844063d7ce2653bd91aac9.

**Comment by daftmugi** [comment]
This is a nice change. I like it.

An issue I found is that if there is an error loading a save file, the plaque stays on the screen without any indication of the error. So, showing the console on error would be nice. To test, `load nofile` at the console.

As a nitpick, when loading from the console, it would be nice if the console view did not jump (close and open again) and rather always stayed open.

Thank you
