### ISSUE TITLE
QuakeC "coredump" function crashes ironwail

### ISSUE THREAD

**Issue by 4LT** [andrei-drexler/ironwail#131]
According to defs.qc, `coredump` (builtin # 28) should print all edicts, but instead crashes ironwail with the following printed:

```
ERROR-OUT BEGIN

Shutting down SDL sound

QUAKE ERROR: PR_SwitchQCVM: A qcvm was already active

```

This was observed by executing the command `impulse 127` in Copper

**Comment by andrei-drexler** [comment]
Thanks, fixed in c901f183be4019433b174d8dc4a8577fe4441c62.
