### ISSUE TITLE
[feature request] hide con_notify stuff in viewsize 130, too

### ISSUE THREAD

**Issue by bleedforever** [andrei-drexler/ironwail#135]
the new `viewsize 130` is great for screenshots! i love it! my snapshot alias is much smaller -- thank you kindly!

but, i still do `con_notifytime -1` in my alias before taking a screenshot, and `con_notifytime 3` after -- otherwise i'll end up with something like `Wrote screenshots/start_2022-09-06_21-33-22.png` at the top left of screenshots, occasionally

so, i was wondering if `viewsize 130` could hide con_notify stuff as well, like it does for the hud and crosshair and stuff

**Comment by andrei-drexler** [comment]
I'm a bit hesitant to remove even more functionality with viewsize 130, and in fact I'm already having second thoughts about the feature altogether. It's useful for experienced players, but potentially confusing for newbies who might activate it by mistake and not know how to get back to 'normal' settings. I might actually end up removing viewsize 130 in favor of having a separate screenshot_clean command with the same effect, preferably exposed in the UI for discoverability. I'll have to think about this some more, though, but for now I guess I'm still keeping it. You do have a point about the text, though, so after commit 7728619b3cceb6492c8bedac2f7a406e3d778d01 notify and centerprint text is hidden automatically when you take a screenshot with viewsize 130 - it's still there during gameplay, and you still get a confirmation after each screenshot, just that it won't show up in the actual pics, which I think is a good compromise.
