### ISSUE TITLE
issue with swinging blades in AD

### ISSUE THREAD

**Issue by Flecked42** [andrei-drexler/ironwail#137]
Swinging blades are black in ad_magna and ad_necrokeep

The blades do look correct in QuakeSpasm though.
![ironwail0001](https://user-images.githubusercontent.com/90434262/192169841-afc46e7e-9955-4d46-a208-c37980f577e4.png)
![ironwail0002](https://user-images.githubusercontent.com/90434262/192169843-0a4395d8-da91-4e6c-8fd4-e4dc6adbfe09.png)
There's also swinging blades in ad_lavatomb, but those look good.

**Comment by andrei-drexler** [comment]
Thanks, already fixed in https://github.com/andrei-drexler/ironwail/commit/ed0e44fbed3b0f25c602666a4d312150bb1105bd.
