### ISSUE TITLE
[Bug] Odd Rendering Bug with Higher "r_wateralpha" Values

### ISSUE THREAD

**Issue by MA113822** [andrei-drexler/ironwail#139]
There seems to be some sort of problem with the rendering of transparent water with higher values of r_wateralpha

![start_2022-10-02_17-43-34](https://user-images.githubusercontent.com/114884081/193477689-56b49143-809a-47ce-b396-7b81c21e50da.png)
r_wateralpha "0.9"

GL_VENDER Intel
GL_RENDERER Intel(R) HD Graphics 530
GL_VERSION 4. 3. 0 - Build 26. 20. 100. 7325

**Comment by daftmugi** [comment]
Well, that looks odd.

Which version of Ironwail are you using?
Which map is this?
What is the `viewpos` value?

**Comment by andrei-drexler** [comment]
It's the id1 start map, the hallway to episode 4, with r_novis 1 (or external vis). Unfortunately this is the reality of alpha blending - when there are multiple surfaces overlapping on screen, the end result depends on the order they're drawn in, and this is especially noticeable with higher alpha values (closer to opaque). You can see [this](https://user-images.githubusercontent.com/5121829/194625889-19820d4d-baaa-4feb-8fe8-3357730fd8e6.png) in QS and vkQuake, as well, from the other side. Fixing it requires either sorting triangles based on camera depth, which AFAIK no Quake engine does (and even if they did, it still wouldn't work in all cases - e.g. intersecting geometry), or some kind of order-independent transparency method, which I've added in a55cf51cca2d8622bd6d54fb54db1cd240a9cbcb. It's still not perfect, and it does come with a performance cost, but it should look at least more plausible in most cases and, as the name says, the result no longer depends on surface order:

|r_oit 0|r_oit 1|
|---|---|
|![r_oit 0](https://user-images.githubusercontent.com/5121829/194624234-86f20217-bdb2-4aff-b980-c036d2cbccd7.png)|![r_oit 1](https://user-images.githubusercontent.com/5121829/194624267-cb0892ad-a61d-4720-b7e2-febc4a2d6ed8.png)|
