### ISSUE TITLE
Autocompleteion on "sky" command in console

### ISSUE THREAD

**Issue by bstordeur** [andrei-drexler/ironwail#141]
A small quality-of-life thing, but if we could get auto-completion on sky file names when using the sky command in the console, that would be pretty awesome.
It's always a pain to browse through long skybox names to test and find the one you want for your map, having auto-completion would really help (it would have to be a bit smart and auto-omit the placement suffix at the end of the file names).
(Reminded of this because of Makkon's just released sky pack.)

**Comment by andrei-drexler** [comment]
I was actually thinking about this feature just now - implemented in 3738161bb840b3dce495fbb24370c1c619b06819. I've also added a new `skies` command (2140ec8c3116687d20f1d32b407cefcbbf04349b) that lists all available skies, with an optional filter argument (e.g. `skies moon` will only list skies containing the word `moon`).
