### ISSUE TITLE
[Bug] Texture filtering turns off in Lightmap

### ISSUE THREAD

**Issue by 1Arttis** [andrei-drexler/ironwail#142]
Texture filtering turns off in lightmap once i turn off view models

With viewmodels
![ironwail0023](https://user-images.githubusercontent.com/117333748/199649740-a501ca48-594d-4e59-a261-8c0e9e87917b.png)

Without viewmodels
![ironwail0022](https://user-images.githubusercontent.com/117333748/199649767-c5d9af32-c39d-47db-bee9-8a816a1ab3fa.png)

So far as i know, this only happens in this WIP map which is running on Progs_Dump 3.00

**Comment by andrei-drexler** [comment]
Closing this, since you said on Discord a while ago that it no longer happens with a more recent test build (probably due to 40d24fca99636b3a51d3f1dc0f38f1bd3fcc22f9). If you do notice it again, please feel free to re-open this issue.
