### ISSUE TITLE
[Suggestion] Have status bar side-tiles scale with status bar

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#150]
With the ability to scale nearly all the 2D elements in the game, it feels like it would only make sense if the brown side-tile textures also scaled respectively with the status bar size, that way the scaling feels more uniform.

**Comment by andrei-drexler** [comment]
Good idea, added in b82da1df62588b2d04d9bf9d3c6f156428fbd9f5.
