### ISSUE TITLE
[Bug] Menu mouse controls let you modify the brightness / contrast sliders even when they are not displayed on screen

### ISSUE THREAD

**Issue by victorator** [andrei-drexler/ironwail#162]
If you go to video options and click around you will eventually end up altering the brightness contrast sliders from the menu that is up one level. I think sliders need to be disabled when entering a menu that is down one level. Mouse controls need to be enabled for this bug to appear.

**Comment by andrei-drexler** [comment]
Good catch, thanks! Should be fixed in e4f8a13946bc22ccfc1071b9dbad6dbb2c1900b2.
