### ISSUE TITLE
[Feature Request] Gyroscope and adaptive triggers support for Dualsense

### ISSUE THREAD

**Issue by victorator** [andrei-drexler/ironwail#163]
It would be amazing to have Ironwail support the gyro for gamepads that have them and bind them to +mlook.

Adaptive triggers in dualsense would be another thing to look at.

**Comment by sndein** [comment]
Yamagi Quake 2 has a really good implementation of gyro controls based on SDL's sensor API that would likely make a good reference if someone were to add this to Ironwail. All the functionality is also nicely exposed in the menus and even itsupports flick stick for the right analog stick.
This of course would apply to any controller with gyro that SDL supports, not just the Dualsense.

**Comment by sndein** [comment]
I've started work on adding gyro based on the code from Yamagi Quake 2 over here https://github.com/sndein/ironwail/tree/gyro_aim
Will make a PR once I'm happy with it.
