### ISSUE TITLE
[Bug] Dynamic lights appear fractured

### ISSUE THREAD

**Issue by 4LT** [andrei-drexler/ironwail#164]
Version: build from latest (master branch)

Screenshot taken while firing shotgun:

![d2m1_2023-02-01_20-21-49](https://user-images.githubusercontent.com/3385021/216208161-0bcb85ec-27b8-448b-a579-0faf2e854a4f.png)

OS: Arch Linux 6.1.7
Hardware: Radeon RX 5600 XT

**Comment by 4LT** [comment]
presently updating drivers... (and everything else ;) )

**Comment by 4LT** [comment]
Identified the difference: `vid_fsaamode 1` causes the dynamic lights to appear fractured

**Comment by andrei-drexler** [comment]
This is a driver bug, if you're using open-source drivers please try the proprietary ones (and vice-versa). `vid_fsaamode` is literally a single GL state (glMinSampleShading), and I've tested it on NVidia (GTX 1060, Windows & Ubuntu), AMD (HD 7850, Windows & Ubuntu) and Intel (Atom x7-Z8700, Windows) and it works as expected.

**Comment by 4LT** [comment]
[Created a ticket w/ mesa](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8280)
