### ISSUE TITLE
[Bug/Feature Request] Improved Lerping Beyond 10hz

### ISSUE THREAD

**Issue by KillPixelGames** [andrei-drexler/ironwail#176]
It _appears_ that lerp is locked at 10hz.  For example, my test viewmodel is animated at 20hz and it seems as though approximately every other frame is lerped, causing it look very jittery/jerky.

**Comment by andrei-drexler** [comment]
Should be fixed in https://github.com/andrei-drexler/ironwail/commit/34ca069d2bf44ece4943456fce3c379d144a8acd.

**Comment by KillPixelGames** [comment]
> Should be fixed in [34ca069](https://github.com/andrei-drexler/ironwail/commit/34ca069d2bf44ece4943456fce3c379d144a8acd).

awesome!!
