### ISSUE TITLE
No Folder in 070 Release Zip files

### ISSUE THREAD

**Issue by dumptruckDS** [andrei-drexler/ironwail#178]
Files in previous versions were inside a folder. New version files are loose which makes installation messier in folder with other QS installs. (also is different than the showcase video)

**Comment by eGax** [comment]
![image](https://user-images.githubusercontent.com/9817245/226140861-63184c2d-cb70-460a-bc0a-e88e137456d6.png)

**Comment by andrei-drexler** [comment]
Yup, I reuploaded new zips in the meantime. Thanks for checking, though.
