### ISSUE TITLE
[BUG?] Issue with Ironwail and Nvidia's Shadowplay

### ISSUE THREAD

**Issue by pagb666** [andrei-drexler/ironwail#179]
When I use Nvidia's GeForce Experience to record Ironwail footage the resulting video comes out with terrible frametimes, it even feels like its stuttering... While playing and recording, the game is silky smooth, solid 60fps. This doesn't happen with vkQuake.

If you need additional info, please let me know.

**Comment by dumptruckDS** [comment]
> 

I just did a test and Shadowplay videos are fine on my setup. Maybe post a video somewhere and some other specs from your system.

**Comment by pagb666** [comment]
Shutting down every other single process I can think of doesn't help. I've also tried unplugging my second display, as it has been proven to do weird stuff when recording in rare occasions, no luck either.

Specs:
ROG-Strix 570-E
R5 3600
32gb DDR4-3200
GTX 1070

Video Sample:
https://www.youtube.com/watch?v=TXEzojfOR9g
DxDiag:
https://www.mediafire.com/file/s23rpss12jwz66c/DxDiag.txt/file

**Comment by Calinou** [comment]
Does this occur when recording in windowed mode, or only in (exclusive) fullscreen?

**Comment by garoto** [comment]
If possible, try configuring Shadowplay to capture footage at 59.94FPS. With OBS and OG Doom3, that fixed very similar stuttery output video like yours.

**Comment by pagb666** [comment]
> Does this occur when recording in windowed mode, or only in (exclusive) fullscreen?

Ok, switched from windowed, which resulted on a borderless presentation to fullscreen, and now it works fine. I always use borderless whenever I can and I never had such an issue. Thanks guys! And sorry for bothering you!
