### ISSUE TITLE
Are there any plans to support Vulkan (and MoltenVK) for MacOS support?

### ISSUE THREAD

**Issue by sofakng** [andrei-drexler/ironwail#180]
Are there any plans to support Vulkan (and MoltenVK) for MacOS support?

I'm not a graphics programmer so I'm not sure of the difference between OpenGL 4.3 and Vulkan but I thought Vulkan was the 'newer' graphics API?

This would also open up the possibility of playing on MacOS using MoltenVK (Vulkan to Metal API).

**Comment by Calinou** [comment]
> I'm not a graphics programmer so I'm not sure of the difference between OpenGL 4.3 and Vulkan but I thought Vulkan was the 'newer' graphics API?

While Vulkan is more modern, OpenGL isn't deprecated on Windows/Linux. Vulkan is also more difficult to program for compared to OpenGL, since it's lower-level.

**Comment by sofakng** [comment]
Thanks for the response.  I can understand that OpenGL is easier but hopefully someday this can be migrated to Vulkan so that MacOS can enjoy it as well.  Thanks!

**Comment by sbritorodr** [comment]
Hello, I'm working on using MoltenVK to translate OpenGL4.3 calls to Vulkan since MacOS deprecreated OpenGL. If you wish to help, @sofakng , here is the PR and my fork: #211
