### ISSUE TITLE
[BUG] Remapping mouse controls

### ISSUE THREAD

**Issue by Thornhat** [andrei-drexler/ironwail#184]
With the new release, trying to remap a command to the mouse (in the CONTROLS menu) causes the selection to jump and erroneously map a different command to the mouse button.  Running the bind command from the console works fine. 

Turning "UI Mouse" off won't map the command when the button is pressed. With it enable, the problem described above persists.

Not sure if this is a bug or an issue with my PC. Tried on 2 different computers with separate mice with same results for both.

**Comment by andrei-drexler** [comment]
This was an actual bug, fixed in commit a6458ab8cf8640dbae93616a967bfeb638c01248.
