### ISSUE TITLE
[BUG] UI mouse borks keyboard navigation

### ISSUE THREAD

**Issue by barneycarroll** [andrei-drexler/ironwail#192]
Pressing directional keys navigates as normal but also moves the mouse cursor some measure in that direction. Mouse movement ends and the navigation focus resolves to wherever the cursor happens to be. 

The arrow key <-> cursor movement binding persists outside of Ironwail after toggling the feature off and quitting the Ironwail process.

**Comment by andrei-drexler** [comment]
There's no code for this in IW, it must have been caused either by an accessibility setting (like "Mouse keys") or some other program. Paint, for example, allows moving the mouse using the arrow keys, and while that feature is only supposed to work when the program is focused, I've seen this misbehave in practice (so just having Paint open could have this effect in some cases).
