### ISSUE TITLE
[BUG] r_showbboxes_filter can't be unset

### ISSUE THREAD

**Issue by barneycarroll** [andrei-drexler/ironwail#195]
The feature is incredibly powerful but AFAICT there is no way of clearing the filter — nearest fuge is setting it to `_` but this won't get a hit on the single-word entity classnames.

Perhaps the function could special-case an input of `*` (which AFAICT wouldn't be a valid classname character?) to clear the internal variable?

**Comment by andrey-budko** [comment]
`r_showbboxes_filter ""` ?

**Comment by barneycarroll** [comment]
Thanks, I had no idea quotes worked!
