### ISSUE TITLE
FTEQW compatibility?

### ISSUE THREAD

**Issue by xplshn** [andrei-drexler/ironwail#200]
Is IronWAIL compatible with FTEQW? Which is used for playing FreeCS and FreeHL? Also, are there any plans to use Github actions for making Linux releases?

**Comment by perondeidad** [comment]
I don't think so, the source port is an improvement on quakespasm but not at the same level as FTEQW, the latter adds features such as compatibility with Hexen 2, Quake 2, Quake 3, doom 3 and Half-life; and the support (still primitive) doom 3 and Half life 2

**Comment by xplshn** [comment]
Okay, thanks for answering.
