### ISSUE TITLE
[UI Issue] Rune Icons not displayed

### ISSUE THREAD

**Issue by dumptruckDS** [andrei-drexler/ironwail#203]
Rune icons are not displayed in Modern 1 and Modern 2 HUD styles. Tested in 0.7.0 64bit version.

**Comment by andrei-drexler** [comment]
They are actually displayed, but only temporarily after pickup (they even flash for a second or two), afterwards you have to press TAB to see them. The reasoning was that they're items the player pretty much never has to interact with, so it's not worth having them on screen permanently.

![e1m7_2023-10-06_22-23-39](https://github.com/andrei-drexler/ironwail/assets/5121829/74b22e27-c091-4b7d-b8ea-590887efc103)

**Comment by andrei-drexler** [comment]
I've just pushed a11ae7a5f8563f81191c5663177f1ed5a4c0480f, so now runes are also shown for a few seconds after loading (useful for resuming older saves).
