### ISSUE TITLE
[Question] How to use official mod server?

### ISSUE THREAD

**Issue by muppi090909** [andrei-drexler/ironwail#205]
Hello, how can I use the addons from [the official git repo](https://github.com/kexquake/addons)?
I ran ironwail with
```
ironwail -addons http://kexquake.netlify.app/
```
I am using Manjaro linux. Thank you.

**Comment by andrei-drexler** [comment]
Hey! It looks like the actual protocol for that addon server is `https`, not `http`, so `-addons https://kexquake.netlify.app/` should work. The next ironwail release will have http redirection enabled (added in https://github.com/andrei-drexler/ironwail/commit/694bff9bf1b092b0d43923482c22e332acfee542), which in this case means the `http` version will work as well.

P.S. Not that it makes any difference, but that isn't really an official server, it's just another community one.
