### ISSUE TITLE
QuakeWorld-Style HUD?

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#206]
Would be a nice addition to have a QuakeWorld-style HUD option to round out the set of layouts.

**Comment by Calinou** [comment]
What's the difference between QuakeWorld HUD and vanilla Quake HUD? Are you referring to ezQuake HUDs (which use their own scripting language)?

**Comment by OpenRift412** [comment]
> What's the difference between QuakeWorld HUD and vanilla Quake HUD? Are you referring to ezQuake HUDs (which use their own scripting language)?

I'm referring to this HUD, as seen in the original QuakeWorld:
![image](https://user-images.githubusercontent.com/29780788/235327593-f29db74a-8899-4f4f-ac12-07ed93ad0f2b.png)

**Comment by Calinou** [comment]
I thought this already happened in multiplayer, with the status bar moving to the left: https://github.com/andrei-drexler/ironwail/issues/181

You can make the statusbar background transparent using the settings already.

**Comment by OpenRift412** [comment]
> I thought this already happened in multiplayer, with the status bar moving to the left: #181
> 
> You can make the statusbar background transparent using the settings already.

I'm more referring to the position of the ammo and weapon indicators here.

**Comment by MilkeyWilkey** [comment]
yeah always thought that this was the best one to date and nobody really does it for some reason. my suggestion would be to have main portion centered and guns&ammo as is on the screenshot

**Comment by bangstk** [comment]
A few years ago I wrote a patch for Quakespasm that adds full QW hud support (including mission pack support). I will see if it is easy to port it forward to Ironwail.

**Comment by bangstk** [comment]
@OpenRift412 I finished the patch and opened a pull request #263. Here's a Windows build if you want to try it. Select "QuakeWorld" from the HUD selector in the ingame options.

[ironwail-qwhud.zip](https://github.com/andrei-drexler/ironwail/files/13201063/ironwail-qwhud.zip)

**Comment by OpenRift412** [comment]
> @OpenRift412 I finished the patch and opened a pull request #263. Here's a Windows build if you want to try it. Select "QuakeWorld" from the HUD selector in the ingame options.
> 
> [ironwail-qwhud.zip](https://github.com/andrei-drexler/ironwail/files/13201063/ironwail-qwhud.zip)

Looks good!

**Comment by j4reporting** [comment]
> A few years ago I wrote a patch for Quakespasm that adds full QW hud support (including mission pack support). I will see if it is easy to port it forward to Ironwail.

Could you  please create a pull-up request for quakespasm as well?

**Comment by NightFright2k19** [comment]
It's in the port by now, shouldn't this be closed?

**Comment by OpenRift412** [comment]
> It's in the port by now, shouldn't this be closed?

You're right. Closing.
