### ISSUE TITLE
[Feature Request] Enable title demo playback toggle

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#21]
I think the one thing Quakespasm has missed out on for a long time is its removal of the original title demos playing back on startup. Could we perhaps see an in-menu toggle for this, so we don't have to worry about constantly adding the -fitz parameter all the time?

**Comment by j4reporting** [comment]
such an annoying and useless feature.  :)
I suspect that most users will set this value to "0" anyway. This might be the better default value so as not to deviate from QS and vkquake.

**Comment by OpenRift412** [comment]
> such an annoying and useless feature. :) I suspect that most users will set this value to "0" anyway. This might be the better default value so as not to deviate from QS and vkquake.

And what an annoying and useless comment.

**Comment by andrei-drexler** [comment]
I don't think that comment was meant as a personal attack, I can see why a power user would prefer the game to start up as quickly as possible and without any distractions. I was pretty sure I'd want the feature disabled by default myself, but after having it on for a week or two, turning it off makes the game seem a bit too sterile/not very game-like to me (compared to the Steam rerelease, for example). Starting Quake for the very first time seems very uneventful without demo/music playback.

**Comment by OpenRift412** [comment]
> I don't think that comment was meant as a personal attack, I can see why a power user would prefer the game to start up as quickly as possible and without any distractions. I was pretty sure I'd want the feature disabled by default myself, but after having it on for a week or two, turning it off makes the game seem a bit too sterile/not very game-like to me (compared to the Steam rerelease, for example). Starting Quake for the very first time seems very uneventful without demo/music playback.

Exactly. That's why it's a cvar.
