### ISSUE TITLE
Shrak add-on

### ISSUE THREAD

**Issue by AntiPontifex** [andrei-drexler/ironwail#214]
Perhaps this is already known to the community, but the old Shrak add-on (1997) simply does not work with this source port. Please do NOT take this the wrong way: this port, otherwise, has been simply amazing. Thank you and others for your hard work.

**Comment by NightFright2k19** [comment]
How do you mean, "does not work"? I've made completed the game more than once with this sourceport and had no major issues.

**Comment by AntiPontifex** [comment]
Thank you for responding. I get stuck at this error:

Mouse1 is unbound, Hit F4 to set

**Comment by NightFright2k19** [comment]
To me that looks like a common config issue. Try deleting the .cfg file from the Shrak folder. If that doesn't do it, check if mouse1 is bound in the config file inside the id1 dir.

Also, are you using the patch I made some while ago? It may also fix the issue.

https://quakeone.com/forum/quake-mod-releases/finished-works/281923-inofficial-shrak-v2-1-patch

**Comment by AntiPontifex** [comment]
Funny you should mention the patch: I tried it, as well as unpacking the PAK files and now it works fine. Thank you for your help :)
