### ISSUE TITLE
[BUG] skewed sprites with mangled player camera

### ISSUE THREAD

**Issue by KillPixelGames** [andrei-drexler/ironwail#218]
VP parallel upright sprites, WinQuake  vs IW
![image](https://github.com/andrei-drexler/ironwail/assets/24704461/65820963-e7ef-4096-b984-9fdb9a1275d9)
![e1f1_2023-05-19_09-35-02](https://github.com/andrei-drexler/ironwail/assets/24704461/b03c9e95-a281-468c-b500-3261139ba315)

**Comment by andrei-drexler** [comment]
Thanks for reporting this, fixed in https://github.com/andrei-drexler/ironwail/commit/232c177905ecdba7ad8f5a4b46e11e1ec9e2fec8.
