### ISSUE TITLE
[Feature Request] Insert disabled by default in console

### ISSUE THREAD

**Issue by mooreye** [andrei-drexler/ironwail#232]
When you want to prepend text in console, it will actually overwrite letters to the right. To disable this, you have to press Insert. QSS had this no-replace behavior by default, would be nice to see this here too

**Comment by andrei-drexler** [comment]
Good idea, changed in https://github.com/andrei-drexler/ironwail/commit/8f055a80fdedb73261eb246340918b43e0bffb78.
