### ISSUE TITLE
[Issue] HIP2M4 texture glitch

### ISSUE THREAD

**Issue by NightFright2k19** [andrei-drexler/ironwail#234]
When using the QuakeEX version of SoA (Update 4.1), the exit gate of HIP2M4 is untextured.

Affected textures: wexit01, exit02_3

![hip2m4_gate](https://github.com/andrei-drexler/ironwail/assets/54737241/b0233cc2-cbf2-4784-9acf-26571ddd8588)

**Comment by daftmugi** [comment]
Duplicate of #230, perhaps?

**Comment by NightFright2k19** [comment]
Alright, didn't see that one. This one can be closed, then.
