### ISSUE TITLE
Increase progs execution runaway loop limit

### ISSUE THREAD

**Issue by Flecked42** [andrei-drexler/ironwail#237]
Info is on QS https://github.com/sezero/quakespasm/issues/58

**Comment by acl-git** [comment]
This would be wonderful, am running into this issue with a current map that doesn't load unless the limit is raised.

**Comment by andrei-drexler** [comment]
The limit has been increased to 16M (from 100K) after a sync with QS (https://github.com/andrei-drexler/ironwail/commit/22f442213c7de4051b3da330044c99a5ae0c3871), which brought in https://github.com/sezero/quakespasm/commit/26b3954bf631292a6cb580334e44531c5478e099.
