### ISSUE TITLE
How do I get the 2021 weapon models ingame?

### ISSUE THREAD

**Issue by adhdandy** [andrei-drexler/ironwail#252]
I am running Ironwail from inside the 2021 "rerelease" folder, but it's still using the old weapon models.

**Comment by Konkonfaux** [comment]
Ironwail doesn't support the md5 models from re-release. VkQuake and Quakespasm-spiked do. But you can use some mdl conversions like [this one](https://www.quaddicted.com/forum/viewtopic.php?id=1017).

**Comment by adhdandy** [comment]
Maybe something that can be implemented in a future update? 
I guess for now I'll stick to VkQuake.
