### ISSUE TITLE
[PATCH] option to build without curl (downloads) support

### ISSUE THREAD

**Issue by sezero** [andrei-drexler/ironwail#256]
In case the user doesn't need it or doesn't have a new-enough curl version.

(Couldn't create a pull request, because can't fork your repo as it is already a for of my qs.)

[0001.patch.txt](https://github.com/andrei-drexler/ironwail/files/12791247/0001.patch.txt)

**Comment by alexey-lysiuk** [comment]
> (Couldn't create a pull request, because can't fork your repo as it is already a for of my qs.)

Push changes to a branch in your repository, press **New pull requests** button on **Pull requests** tab of Ironwail, and select the branch from your repository in the second drop-down list (after an arrow).

**Comment by sezero** [comment]
> > (Couldn't create a pull request, because can't fork your repo as it is already a for of my qs.)
> 
> Push changes to a branch in your repository, press **New pull requests** button on **Pull requests** tab of Ironwail, and select the branch from your repository in the second drop-down list (after an arrow).

Nope, won't do that..

**Comment by andrei-drexler** [comment]
Added in https://github.com/andrei-drexler/ironwail/commit/eaa830d50efa44988ecaf7cd057e32154b70b094, thanks!

**Comment by sezero** [comment]
You're welcome. It's crude though, could have been done better to exlcude much more code, but does the intented job anyway.
