### ISSUE TITLE
Dual Monitor Focus

### ISSUE THREAD

**Issue by Dreded** [andrei-drexler/ironwail#27]
To be fair this issue is present in quakespasm but thought id mention it, the focused window is not the game window on initial startup until the game window is clicked on with mouse.

Confirmed that it doesn't happen with only one screen.

**Comment by andrei-drexler** [comment]
I'm using a dual-monitor setup myself, but I can't reproduce this using either Win7, Win10 or Ubuntu 20.04. That being said, I've added a call to SDL_RaiseWindow after SDL_ShowWindow in https://github.com/andrei-drexler/ironwail/commit/c40d82105e2618a4a31e4598dbc03681585c3346, which might help, but other than that there's not much I can do.
