### ISSUE TITLE
Controller Input Ignores cl_alwaysrun 0, Always Scaling to Maximum Speed

### ISSUE THREAD

**Issue by mmillar-bolis** [andrei-drexler/ironwail#277]
Earlier versions of Ironwail, as well as Quakespasm, honored `cl_alwaysrun 0` with controller input. This allowed a player to move at a lower pace while binding `+speed` to a button for faster pace when needed.

It appears that something broke in recent updates of Ironwail. While keyboard input still works as expected with `cl_alwaysrun 0`, the controller appears to be permanently stuck scaling to maximum speed.

Version: 4c6f7f9
OS: Windows 10 21H2

---

EDIT: This appears to be a problem on my end. I am very sorry for cluttering your issue history.

**Comment by andrei-drexler** [comment]
> EDIT: This appears to be a problem on my end. I am very sorry for cluttering your issue history.

No worries!
