### ISSUE TITLE
Mouse Controls are unbindable

### ISSUE THREAD

**Issue by tunbridgep** [andrei-drexler/ironwail#282]
Right Click, Left Click and all other mouse buttons are not bindable in the Controls menu, they probably should be.

I want to bind quick zoom.

Expected Behaviour: Press Enter to start binding, right click to set quick zoom to right click

Actual Behaviour: Press Enter to start binding, right click does absolutely nothing. Nor does any other mouse button.

**Comment by andrei-drexler** [comment]
Thanks for reporting this, already fixed in commit a6458ab8cf8640dbae93616a967bfeb638c01248 (initially reported in #184).
