### ISSUE TITLE
[Feature Request] Speedometer

### ISSUE THREAD

**Issue by tunbridgep** [andrei-drexler/ironwail#284]
Similar to the one in JoeQuake:
https://www.reddit.com/r/quake/comments/m654g4/quakespasm_speedometer_or_draw_speed/

The short version is: A command such as `show_speed` that prints the players current speed to the corner of the screen.

**Comment by andrei-drexler** [comment]
Already added in d50b1974d7629a51105b954e59020e934c6e0223 :)

**Comment by zbelios** [comment]
> Already added in [d50b197](https://github.com/andrei-drexler/ironwail/commit/d50b1974d7629a51105b954e59020e934c6e0223) :)

scr_showspeed doesn't seem to work on Ironwail 0.70.
Typing `scr_showspeed 1` into the console displays a message along the lines of: "No cvars/commands contain scr_showspeed"
Was this command removed or something?

**Comment by andrei-drexler** [comment]
The cvar was added after the 0.7 release, it will be available in the next version.
