### ISSUE TITLE
Odd screenspace dithering always present despite r_softemu being 0

### ISSUE THREAD

**Issue by Terraformer9x** [andrei-drexler/ironwail#286]
I have no idea if this is intentional behavior or not but I assume it isn't.

I've noticed that Ironwail has always odd screenspace dithering going on despite `r_softemu` being set to 0.

Here's a screenshot, the resolution is 2560x1440:
![e1m1_2023-12-22_05-05-05](https://github.com/andrei-drexler/ironwail/assets/83795041/3bc0627b-0d0b-48d7-857f-47e98c1724f0)

It's very hard to notice unless you zoom in, so here's a zoomed in portion of the left wall in the above screenshot:
![image](https://github.com/andrei-drexler/ironwail/assets/83795041/05e62905-9bab-45ba-a188-dd050a53b087)

The oddity becomes more noticeable when `r_scale` is set higher than 0, here it is set to 3:
![e1m1_2023-12-22_05-05-05](https://github.com/andrei-drexler/ironwail/assets/83795041/75811c7e-4972-43dd-a338-ef9e9cf3d088)

And here, `r_scale` is set to 6:
![e1m1_2023-12-22_05-05-13](https://github.com/andrei-drexler/ironwail/assets/83795041/b72b1b20-ff63-42c5-895b-7c1d79828bf6)

Again, I have no idea if this behavior is intentional and I can not find any `cvar` linked to turning off this weird dithering effect despite the engine advertising dithering as being something that's optional.

**Comment by OpenRift412** [comment]
Actually, this behavior is also subtly present in when r_softemu is set to 3. It isn't really present when cranking up the r_scale variable, but if you look closely at the weapons you can see a slight dither pattern in certain places.

**Comment by Terraformer9x** [comment]
Closing due to recent commits adding options for dithering.
