### ISSUE TITLE
[Feature Request] r_showfields command identical to the one in FTE

### ISSUE THREAD

**Issue by ZecChelovek** [andrei-drexler/ironwail#290]
Wherein you can see an object's entire being: classname, spawnflags, everything. If the people in charge of Ironwail are unfamiliar with how that looks I can provide a screenshot.

**Comment by andrei-drexler** [comment]
Added in e0c3a51c692aad972600958ad725b9e348eb2b27:
![r_showfields](https://github.com/andrei-drexler/ironwail/assets/5121829/c3b71a8a-aa07-4b39-9531-18ff66f0f393)

Also changed `r_showbboxes` a bit to highlight the entity in the center of the screen and show its number and classname:
![r_showbboxes](https://github.com/andrei-drexler/ironwail/assets/5121829/d1f4e78f-edc6-450d-85c6-cc806c5a1706)

`r_showfields` and `r_showbboxes` can be active at the same time, in which case we only show the full field list:
![r_showbboxes+r_showfields](https://github.com/andrei-drexler/ironwail/assets/5121829/258f2c23-b171-47b5-9d76-e8a9883de785)
