### ISSUE TITLE
[Bug] Rewind demo control ends demo playback

### ISSUE THREAD

**Issue by 4LT** [andrei-drexler/ironwail#293]
Version: Latest commit
OS: Arch Linux

Quits to console upon pressing left arrow.  No output is printed as a consequence.

**Comment by andrei-drexler** [comment]
I'll need a bit more info, because I've tested it with demos from id1, ad and alk1.2 and I haven't seen this issue, but I've only tested on MSVC. Does it happen with any demo, even the original startdemos?

**Comment by 4LT** [comment]
I figured it out, there's an integer underflow on "right key" - "left key"

**Comment by andrei-drexler** [comment]
Can you give eb1841c2a85f58c24f1e536a0ee9614a782df6f3 a try? That should fix it.

**Comment by 4LT** [comment]
Yeah, it works.  I made my own fix already, in case you might prefer that:

https://github.com/4LT/ironwail/commit/1d15ecd3b7de89636f61a20213b2cfd39a9146b1

It's more explicit in its casts.  I also explicitly zero'd the demo_rewind pointers while I was trying to track down the issue

**Comment by andrei-drexler** [comment]
I like the explicit casts, but zeroing out those pointers in `CL_PlayDemo_f` will leak memory the second time it's called. Those buffers are meant to grow and then be reused - `VEC_CLEAR` doesn't free the memory that's already been allocated, it simply sets the size to 0. As for static memory - it does indeed get zeroed on initialization, and fortunately it's not an implementation detail, it's actually mandated by the standard, so you *can* rely on it :)

Anyway, thanks for reporting and investigating this!
