### ISSUE TITLE
[BUG/ERROR] Episode Enyo throws "Image_LoadTGA: gfx/env/map1_rt.tga is not a type 2 or type 10 targa (255)" error

### ISSUE THREAD

**Issue by TheDwellerInDarkness** [andrei-drexler/ironwail#295]
Episode Enyo's start/hub map loads fine, but it throws this error after entering the teleporter to load into the next level and crashes. I have no clue if it's an error caused by Ironwail or Episode Enyo, but I figured it'd be worth it to report the issue anyway.

**Comment by andrei-drexler** [comment]
That's an issue with the actual data files:
> In the Kex-distributed pak, the skyboxes are JPGs renamed as TGAs to save on memory, because that's the only way that it can read a JPG skybox as it's hard-coded to only read .tga files. Other ports require the image format to follow the file extension so they don't like this hack. The standalone build have the skyboxes back as proper high resolution TGAs both in name and format, so it'll work fine in every port.

(from [reddit](https://www.reddit.com/r/quake/comments/19882vp/comment/kibnaih/))

The next IW version will actually be able to cope with this hack, but until then you could give the [standalone Enyo build](https://poppyworks.itch.io/episode-enyo) a try, if you haven't already.
