### ISSUE TITLE
menu_maps question(menumaps.lmp)

### ISSUE THREAD

**Issue by MissLavender-LQ** [andrei-drexler/ironwail#300]
will there be a **menumaps.lmp** akin to the menumods.lmp 
already made one for librequake in case y'all add one
![image](https://github.com/andrei-drexler/ironwail/assets/51702517/8f529dbf-098e-4b54-8141-82a815c70705)

**Comment by andrei-drexler** [comment]
The `Levels` menu is meant to be accessed via `Singleplayer`, so the corresponding lmp file is [gfx/sp_maps.lmp](https://github.com/andrei-drexler/ironwail/blob/master/Misc/pak/gfx/sp_maps.lmp). If you rename the LQ one to that it should show up in the UI.

**Comment by MissLavender-LQ** [comment]
ah heard had not seen it in ironwail.wad
