### ISSUE TITLE
[Bug] /n added in `maps`

### ISSUE THREAD

**Issue by timbergeron** [andrei-drexler/ironwail#303]
the description parsing is adding a space in `maps` print

![image](https://github.com/andrei-drexler/ironwail/assets/68674590/645b25e8-59c6-4022-9798-8d8727921e65)

foundry beta 3 can be downloaded at: 
https://maps.quakeworld.nu/all/

this also happens with [bsdm8.bsp](https://maps.quakeworld.nu/all/bsdm8.bsp) and a few other maps

**Comment by andrei-drexler** [comment]
The newlines are already there in the map descriptions, which I think is incorrect (should've been `"\n"` instead, AFAIK). I've added code to sanitize them in c123e174856d0f5f03d1d568627d71842add7613.

**Comment by timbergeron** [comment]
awesome, quick fix :)
