### ISSUE TITLE
[bug] with gl_overbright_models

### ISSUE THREAD

**Issue by lavenderdotpet** [andrei-drexler/ironwail#305]
## ironwail doesn't display fullbrights correctly in gl_overbright_models 0

here is a pre setup game with a save in front of the torches
this is here so u can test the issue locally 
i removed all sound and music and maps other then start and dev to get the file size down
### ironwail `gl_overbright_models 0`
![dev_2024-02-27_15-28-29](https://github.com/andrei-drexler/ironwail/assets/51702517/d153bccb-b111-472f-a0b8-51c8216d3955)

### ironwail `gl_overbright_models 1`
![dev_2024-02-27_15-29-50](https://github.com/andrei-drexler/ironwail/assets/51702517/3fb7c1e9-1c6c-4f57-a555-fc79a343a02d)

### qss/quakespasm `gl_overbright_models 0`
![spasm0001](https://github.com/andrei-drexler/ironwail/assets/51702517/99030f88-efca-4af0-8ea5-5bc855f2fa02)

### qss/quakespasm `gl_overbright_models 1`
![spasm0000](https://github.com/andrei-drexler/ironwail/assets/51702517/9a028b82-3996-4352-a494-226d104da7ad)

**Comment by MissLavender-LQ** [comment]
# side by side gif
![iwqs](https://github.com/andrei-drexler/ironwail/assets/51702517/8da86c0e-f386-4a96-b77e-094101f4f8ff)

**Comment by lavenderdotpet** [comment]
was an issue with the librequake colormap.lmp

which was fixed here https://github.com/lavenderdotpet/LibreQuake/pull/152
