### ISSUE TITLE
[BUG/CRASH]: Ironwail Crashes with mod Enyo

### ISSUE THREAD

**Issue by shmabler** [andrei-drexler/ironwail#316]
The Enyo mod/game crashes Ironwail when stepping into the portal in the start map.
Error displayed in terminal:
QUAKE ERROR: Image_LoadTGA: gfx/env/map1_rt.tga is not a type 2 or type 10 targa (255)

Additionally, the opening Enyo scenery picture (as seen in QuakeSpasm for example) is not displayed and instead it goes directly to the main menu.

**Comment by andrei-drexler** [comment]
This is an issue with the data files in the Kex version (#295). For source ports there's a separate download [here](https://poppyworks.itch.io/episode-enyo).

As for the initial scenery, it's probably because `cl_startdemos` is 0. Setting it to 1 should fix that.

**Comment by shmabler** [comment]
Ah, OK. There still remains the issue of how do we get it to use the source port version folder and stop using the .rerelease? Ironwail seems to copy this folder on start. We could uninstall the enyo mod in the kex engine which would fix the problem, but I'm not sure this is the best solution.
