### ISSUE TITLE
Map Crash in 0.4.0

### ISSUE THREAD

**Issue by Big-the-Fat** [andrei-drexler/ironwail#32]
Playing Leptis Magna in Arcane Dimensions.  The map crashed to the console while fighting the big boss with this message:

packet overflow
sz_getspace: overflow

**Comment by andrei-drexler** [comment]
I was able to reproduce this in vanilla QS, too. Fixed in https://github.com/andrei-drexler/ironwail/commit/1d11e9eb6cba3c8e7f9f4f6ac6e2842e3b26df4b
