### ISSUE TITLE
process can hit  max open files limit  when loading  save games

### ISSUE THREAD

**Issue by j4reporting** [andrei-drexler/ironwail#320]
Something is going very wrong with the handling of pak files.

how to reproduce:
1. ironwail -game ad
2. map ad_magna  
3. save quick
4. keep reloading with the F key   until message error: couldn't open appears

![image](https://github.com/andrei-drexler/ironwail/assets/45177907/c7a79ce8-6cab-4199-8864-f3e4ef3f6f40)

at his point  any load or save will fail  and  load/save  menu will not show any existing save files s[0-19].sav  
not reproducible in  qspasm

each map start or load of savegame  will leak additional filedescriptors  for AD/pak0.pak file 

Process monitor shows  many ClossFile lines at process end for ad/pak0.pak   with this filter  

![image](https://github.com/andrei-drexler/ironwail/assets/45177907/29fd6872-85a5-4f8d-a481-a57bc9510b9f)

**Comment by andrei-drexler** [comment]
Thanks for the detailed report! Should be fixed in 3ce9048874434f70012072c2d3747501c27943cd.
