### ISSUE TITLE
Classic underwater warping is not compatible with renderer scaling

### ISSUE THREAD

**Issue by ebaender** [andrei-drexler/ironwail#321]
Seems like the classic underwater warping shader is applying some kind of filtering. Doesn't look like linear but definitely not nearest, which it should be if you're using a scaled renderer.

I hope this can be fixed, the GLQuake warping does not have this issue but is just way less interesting. Here is a comparison off all three underwater settings with `r_scale 8` to make the filtering as visible as possible.

![Screenshot 2024-06-30 045327](https://github.com/andrei-drexler/ironwail/assets/29549891/5bcf78cc-0498-436f-94e9-1520c1a5546f)
![Screenshot 2024-06-30 045334](https://github.com/andrei-drexler/ironwail/assets/29549891/9f643b13-3b35-4467-ae7e-da4feeff9641)
![Screenshot 2024-06-30 045339](https://github.com/andrei-drexler/ironwail/assets/29549891/203873b2-0669-4778-872a-e44ff921bdb3)

**Comment by andrei-drexler** [comment]
Fixed in https://github.com/andrei-drexler/ironwail/commit/33ec4a23890ae96f5af09635a845fe6fd2ef6036.
