### ISSUE TITLE
creates  empty directoriy when started with  option -game <nonexisting dir>

### ISSUE THREAD

**Issue by j4reporting** [andrei-drexler/ironwail#325]
starting ironwail from cli  with the `-game  <mod>`  option will  create an empty directory if mod name doesn't exist.

Maybe print an error message and don't start or fail back to ID1  *and*  don't create any empty directory in gamedir

**Comment by andrei-drexler** [comment]
Added in https://github.com/andrei-drexler/ironwail/commit/199deb0291c206e0bb54f267e4d44b0001d5cf13.
