### ISSUE TITLE
linux ironwail blue dots issue

### ISSUE THREAD

**Issue by lavenderdotpet** [andrei-drexler/ironwail#326]
![image](https://github.com/user-attachments/assets/3ce296ec-808f-45e8-a308-c82b0a30aa80)

https://github.com/user-attachments/assets/06af7fcf-f116-4288-89ee-247005767b54

### these blue noisy dots show up on iron wail on linux for me
also am running a amd gpu

**Comment by sndein** [comment]
I've experienced this as well. Also on Linux, with an RX 7800 XT. Happens only very rarely.
I know I've also seen this happen in Yamagi Quake 2 and possibly other games, can't quite recall, so I suspect the issue lies deeper than Ironwail.

**Comment by lavenderdotpet** [comment]
> I've experienced this as well. Also on Linux, with an RX 7800 XT. Happens only very rarely. I know I've also seen this happen in Yamagi Quake 2 and possibly other games, can't quite recall, so I suspect the issue lies deeper than Ironwail.

![image](https://github.com/user-attachments/assets/af9e3ec6-0284-4903-ab29-7ed31f964ea2)
my gpu

**Comment by lavenderdotpet** [comment]
![image](https://github.com/user-attachments/assets/845ff688-04c1-4ae2-970c-a1bbe88ec267)
additional ideas from the quakemapping discord

**Comment by lavenderdotpet** [comment]
# UPDATE
the blue dots only show when transparency is set to "Modern" 

https://github.com/user-attachments/assets/90fd50cc-4aa3-43bc-a9f1-95eb029e40be

**Comment by andrei-drexler** [comment]
It's a driver bug (linked above). It looks like the code was fixed a couple of months ago, so a driver update should get rid of the artifacts at some point.
