### ISSUE TITLE
(Bug) Flickering textures 

### ISSUE THREAD

**Issue by PolterG** [andrei-drexler/ironwail#330]
While looking around the game loads the 'wrong' textures, so I have walls made of lava, invisible (dead) enemies etc. I don't have this problem with alternatives, or vanilla Quake (original). I am using an AMD GPU, OS and drivers are all up to date. 

I also just found it only happens when renaming the ironwail.exe to glquake.exe. If I boot the ironwail.exe without renaming it first I don't experience any issues.

https://github.com/user-attachments/assets/69b43cba-b68e-4f5a-911e-b8256c96a37c

**Comment by andrei-drexler** [comment]
It's very likely the driver has a special code path for glquake.exe, and I have no control over whatever workarounds are applied there. If you just want to play Quake and you already have the game on Steam, GOG or EGS, you can just unzip the Ironwail release anywhere outside the actual Quake dir and it should detect the install dir automatically, without needing to rename the executable or anything of that sort.
