### ISSUE TITLE
Game becomes unresponsive after `menu_mods`

### ISSUE THREAD

**Issue by daftmugi** [andrei-drexler/ironwail#333]
If the mods menu is opened from a bound key or the console, the game becomes unresponsive (locks up) after pressing `ESC`.

To reproduce:
1. `map start`
2. `menu_mods` to open the mods menu
3. Press `ESC` to return to the game

**Comment by andrei-drexler** [comment]
Thanks, should be fixed in https://github.com/andrei-drexler/ironwail/commit/6f1fa0b83a0a210bc1b28977840dc545c53398eb.
