### ISSUE TITLE
[Bug] Vanishing Geometry

### ISSUE THREAD

**Issue by Immorpher** [andrei-drexler/ironwail#34]
I am not enough of an expert to know if this is an engine-related bug or a map-related bug. But I found some nearby geometry which seems to vanish depending on my distance from it in a custom map: https://youtu.be/CXo08_FyqxA

This is from Brendy's hard driven map...
Download: https://archive.org/details/brendy2
Discussion : https://www.quaddicted.com/forum/viewtopic.php?id=1186

I did have an model replacement pack on top to add some of the Remaster models and a few other things.

**Comment by andrei-drexler** [comment]
It's a mapping bug - there's a "skip" brush in front of that geometry. "Skip" is special - the faces aren't rendered, but the map compiler treats them as visibility blockers. This happens in all engines (unless `r_novis 1` is used, which I don't recommend).
