### ISSUE TITLE
regression:   input buffer not cleared in console

### ISSUE THREAD

**Issue by j4reporting** [andrei-drexler/ironwail#341]
recent git master  builds  are affected  since mid August   

bring down the console with  the  key left of  1  ( usually it's the  grave  / tilde  key on US-keyboard )  and start typing a command .

Win10,    keyboard configured to  US-international   ( dead keys for grave / tilde and some other  keys)

**Comment by andrei-drexler** [comment]
I can't seem to repro this. Bringing down the console, typing something (without pressing enter) and then dismissing the console clears the buffer. Are there any other steps involved?

**Comment by andrei-drexler** [comment]
Are those mingw builds by any chance? I'm not seeing this when compiling the latest code with MSVC.


https://github.com/user-attachments/assets/a94a134e-3be6-4651-bd90-04ba1512aa32

**Comment by NightFright2k19** [comment]
I can confirm this issue. First typing into console always gets screwed up.

**Comment by andrei-drexler** [comment]
Thanks, I was finally able to reproduce the issue after by dismissing the console with ESC instead of tilde. https://github.com/andrei-drexler/ironwail/commit/db6e2f0e77db93df5adf79225c9537b2b7953d91 should fix it.
