### ISSUE TITLE
Crash while playing Alkaline map Core Meltdown

### ISSUE THREAD

**Issue by srkowatch** [andrei-drexler/ironwail#342]
Host_Error: SOLID_BSP with a non bsp model (misc_bob at 2655.964355
-1336.000000 1112.000000)

The map crashes and this is the error in the console.

I tested this map on VkQuake and did not have this issue

Using dev build 24e79a2 and the Immortal Lock version from slipseer

**Comment by andrei-drexler** [comment]
I'll need more info, because it doesn't seem to crash for me. Does it happen immediately after loading the map, or after playing for a while? It it's after a while, is it triggered by a particular event (e.g. entering an area, pressing a button, killing a monster etc.)? If it's consistent, can you make a savefile before it crashes? Also, which Alkaline version are you using? Do you have any custom pak files in there? Is IW using the same basedir as VkQuake (you can use the `path` console command to find out)?

**Comment by alexey-lysiuk** [comment]
https://www.quake-info-pool.net/q1/qfix.htm#movetype_push

**Comment by srkowatch** [comment]
VkQuake is using the same basedir since I copy pasted the same folders from Ironwale into Vkquake.

Its Alkaline ver 1.2.2e with some sounds I modified

here is a save file, just change is to .sav
[s4.txt](https://github.com/user-attachments/files/17267567/s4.txt)  

Just jump into the slime and swim into the left hand body. It crashes to console every time for me.

**Comment by alexey-lysiuk** [comment]
VkQuake has this issue fixed, https://github.com/Novum/vkQuake/commit/d9d4be488436c50afcc75b2aacdb50127f6546ab. Like commit message says, it was derived from QSS.

**Comment by andrei-drexler** [comment]
Thanks, should be fixed in https://github.com/andrei-drexler/ironwail/commit/bbda318ce9b77ab6a0f900d3f3a6f9588ef00087.

@sezero @j0zzz I think it would be best to add this fix in QS and JoeQuake as well.

**Comment by sezero** [comment]
> Thanks, should be fixed in [bbda318](https://github.com/andrei-drexler/ironwail/commit/bbda318ce9b77ab6a0f900d3f3a6f9588ef00087).
> 
> @sezero @j0zzz I think it would be best to add this fix in QS and JoeQuake as well.

Applied to qs after a minor commit message edit. Thanks.

**Comment by j0zzz** [comment]
> Thanks, should be fixed in [bbda318](https://github.com/andrei-drexler/ironwail/commit/bbda318ce9b77ab6a0f900d3f3a6f9588ef00087).
> 
> @sezero @j0zzz I think it would be best to add this fix in QS and JoeQuake as well.

Applied to joequake too. Thanks!

**Comment by srkowatch** [comment]
Thanks for the swift fix!
