### ISSUE TITLE
Pusher issues in AD_Tears (linked to commit 8a1132a)

### ISSUE THREAD

**Issue by Placo** [andrei-drexler/ironwail#345]
In the map ad_tears, during the true "secret" last fight in the sanctum of tears, pillars are raised with shamblers and fiends inside.
The map is a product of its time and in engines that have not implemented QSS's version of SV_RecursiveHullCheck the fiends are stuck in the pusher pillars and are crushed to death before the pillars can raise properly. 
Still the map was finishable in Ironwail.

Since commit 8a1132a however, the pillars are raised properly, the fiends are not crushed but are stuck halfway in the floor, but more problematic is the fact that the items in the pillars and even a shambler drop below the pusher. The shambler can still use its lightning attack through the floor but the player cannot kill it legitimately, preventing the completion of the map since the shambler is part of a trigger for the rest of the fight.

Seeing how it changed how this map behaves I fear the change might have broken some other maps too, it might be worth a check.

I run IW on win10 on a i7 8700k

**Comment by andrei-drexler** [comment]
Thanks for the detailed report, the issue should be fixed in https://github.com/andrei-drexler/ironwail/commit/f82be5517517aba36eaf0080f278231b61f694e1 (the results should be identical to the unoptimized code).

**Comment by Placo** [comment]
That fixes it, thanks!

**Comment by bstordeur** [comment]
Thanks for this!
Huge regret to not have tested this in vanilla QS before release. :|
