### ISSUE TITLE
Maroooned by MFX+Orl won't load - model w/ too many vertices

### ISSUE THREAD

**Issue by 4LT** [andrei-drexler/ironwail#352]
![image](https://github.com/user-attachments/assets/c3bcb475-7f7c-4018-83b8-38c3ce3ac1bb)

According to Orl, the map/assets should work in FTE and QSS; supposedly it should work in IW as well minus some 3d skybox feature QSS and FTE have.

The files can be found [here](https://www.slipseer.com/index.php?resources/marooned.412/) (Requires [Mjolnir](https://www.slipseer.com/index.php?resources/quake-mj%C3%B6lnir.243/))

**Comment by andrei-drexler** [comment]
Fixed in https://github.com/andrei-drexler/ironwail/commit/df8f9261bfe94bcfe31d38dd678c6888f1c98325 by removing the vertex/triangle limits altogether.
