### ISSUE TITLE
Flickery textures on IW 0.8.0

### ISSUE THREAD

**Issue by basementApe** [andrei-drexler/ironwail#359]
![ironwail_texbug](https://github.com/user-attachments/assets/0afca399-afe3-48d9-a999-3d3d6629fce0)

My specs:
Ryzen 2500U
Vega 8
8MB RAM
Windows 10

**Comment by andrei-drexler** [comment]
I think this is a driver bug, but I have a hunch on what might be triggering it (assuming 0.7 didn't exhibit this issue). Can you give one of [these binaries](https://github.com/andrei-drexler/ironwail/actions/runs/11865890331) a try to see if https://github.com/andrei-drexler/ironwail/commit/41c2962ae69a83678cf9bc0c0a13c32d509c7019 fixes it?

**Comment by basementApe** [comment]
Yup, both exes fix the texture flickering. Mdl render all broken now but I dunno if that's expected

**Comment by andrei-drexler** [comment]
> Yup, both exes fix the texture flickering
Alright. thanks!

> Mdl render all broken now but I dunno if that's expected
That's definitely not expected, the commit didn't touch the MDL code at all. Can you show me what that looks like?

**Comment by basementApe** [comment]
![ironwail_mdlbug](https://github.com/user-attachments/assets/ec0d9b29-33e9-4a42-b8be-da1184801c78)

I switched from vanilla pak0/pak1 to remastered pak0 in the meantime, and everything is fine if I switch back. Maybe an md5 issue that was already there? It wasn't there in 0.7.0 at least that's for sure

**Comment by andrei-drexler** [comment]
Did the remastered models look ok in the official 0.8?

**Comment by basementApe** [comment]
Just to confirm that the latest QSS-M doesn't show any issues with the md5 replacements, so the problem isn't from there (assuming it's the same code as regular QSS)

**Comment by andrei-drexler** [comment]
Thanks! While most of the MD5 code in IW does indeed come from QSS, the rendering is quite different - it uses instancing and performs anim blending on the GPU, for example. I think this is yet another driver bug, but luckily, I have another hunch. Can you try one of [these new binaries](https://github.com/andrei-drexler/ironwail/actions/runs/11869968949) to check if the issue is still present?

**Comment by basementApe** [comment]
Now they look right : ) Coolness!

**Comment by andrei-drexler** [comment]
Great, thanks again for the report and all the testing!
