### ISSUE TITLE
[Feature Request] Model Interpolation Toggle

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#36]
Could we perhaps get a model interpolation toggle to go alongside the software emulation feature?

**Comment by garoto** [comment]
You can already do that with either an alias or with a keybind.

**Comment by OpenRift412** [comment]
> You can already do that with either an alias or with a keybind.

Well yeah, but it's worth having a toggle in the menu for it. Much less of a hassle.

**Comment by garoto** [comment]
I'm not a "menu" driven person myself. I'm perfectly confortable toggling the console and typing commands FWIW.

**Comment by andrei-drexler** [comment]
Added in abfb9f850e0122bfd58a88e8597635dd7759c253.
