### ISSUE TITLE
[Feature Request] Scale Crosshair with rest of HUD

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#38]
It always seemed a bit odd that the HUD scale slider never effects the size of the crosshair. It would probably be more intuitive to have the slider also effect scr_crosshairscale in addition to the other HUD elements.

**Comment by andrei-drexler** [comment]
I've added this in https://github.com/andrei-drexler/ironwail/commit/5efaf7d2ebfdfbd020548e6e43910ff49b616c3e, but I think the way it was before made sense, too: the crosshair is just a marker in the middle of the screen, not something that needs to be read/interpreted in some way like the rest of the UI. Making it too big could actually be a problem. I guess we'll see if anyone complains about this change...

**Comment by OpenRift412** [comment]
> I've added this in [5efaf7d](https://github.com/andrei-drexler/ironwail/commit/5efaf7d2ebfdfbd020548e6e43910ff49b616c3e), but I think the way it was before made sense, too: the crosshair is just a marker in the middle of the screen, not something that needs to be read/interpreted in some way like the rest of the UI. Making it too big could actually be a problem. I guess we'll see if anyone complains about this change...

Well the issue is that that the default is just _ridiculously_ small. Alternatively, crosshair scale could have it's own separate slider instead.

**Comment by mhQuake** [comment]
For the crosshair, I generally use the following pic:

`	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x5f, 0x5f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x5f, 0x5f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x5f, 0x5f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0x5f, 0x5f, 0x5f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x5f, 0x5f, 0x5f, 0xff, 0xff,
	0xff, 0xff, 0x5f, 0x5f, 0x5f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x5f, 0x5f, 0x5f, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x5f, 0x5f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x5f, 0x5f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x5f, 0x5f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff`

It's 16x16 so it's more visible, it still looks satisfactorily "Quake-ey" to me, but also looks more like an actual crosshair rather than just reusing the '+' character.
