### ISSUE TITLE
[Bug] Screenshot extension .pn instead .png

### ISSUE THREAD

**Issue by TMHKR** [andrei-drexler/ironwail#44]
Screenshots are saved with name.pn instead of name.png

Ironwail 0.4.0 x64 on Win10

![pn](https://user-images.githubusercontent.com/6874649/155318272-6f2b7ee1-028c-442b-8067-1ba9aef3ab78.jpg)

**Comment by andrei-drexler** [comment]
Thanks, fixed in f781fee90ac67ad91a3ff77413578193b55d6cc6.

**Comment by TMHKR** [comment]
> Thanks, fixed in [f781fee](https://github.com/andrei-drexler/ironwail/commit/f781fee90ac67ad91a3ff77413578193b55d6cc6).

Nice! One small question, can you please tell me how often are releases compiled? When you fix a certain amount of bugs, or when certain time passes? I'm asking this since I'm just a member of the "common folk" and report bugs as I play :)

**Comment by andrei-drexler** [comment]
It mostly depends on how significant the accumulated changes are. I do try to keep some distance between releases to avoid people just getting tired of manually updating, but if there are any major issues the goal is to patch them as soon as possible. Next release will probably be very soon.

PS bug reports are always appreciated :)

**Comment by TMHKR** [comment]
Thanks, I ask this mainly because of the game-breaking bugs such as #32

**Comment by andrei-drexler** [comment]
I guess I considered that one as lower priority, since it's the same in Quakespasm, and it's been like this for a long time.
