### ISSUE TITLE
[Feature Request] freelook cvar

### ISSUE THREAD

**Issue by mhQuake** [andrei-drexler/ironwail#45]
Allows for control of mouse looking by cvar in addition to by the "+mlook" command. The implementation simply replaces most instances of "if (in_mlook.state & 1)" with "if ((in_mlook.state & 1) || freelook.value)". The exception would be the check that writes "+mlook" to the config file. The "freelook" cvar would also take over the menu option.

The name was standardised as "freelook" in Quake II onwards, so this standard should be followed for player-expected behaviour. The default value is 1, and it should have CVAR_ARCHIVE. 

The primary benefit of this feature is to enable mouse looking to be enabled by default on first run.

**Comment by andrei-drexler** [comment]
First run experience could definitely use some love. Added in https://github.com/andrei-drexler/ironwail/commit/307f1b555972eb637e61c85a6a0206ae8345658d.
