### ISSUE TITLE
[Feature request] underwater audio filter

### ISSUE THREAD

**Issue by Hexaae** [andrei-drexler/ironwail#47]
What about adding a cool audio filter (muffled sound) underwater?

**Comment by GenericJohnDoeNO0** [comment]
Well, i do not know how to program that but: When you enter water and the "breathing cd counts down" would be a good trigger for muffling.

But: You will have problems on some (many?) custom maps, you know never if some mappers did play around that trigger.

**Comment by andrei-drexler** [comment]
I've added a simple filter in https://github.com/andrei-drexler/ironwail/commit/1c0a514e37a67f84ac42f2a9072ea66c41ab6dcb. It's very low-tech (could've been implemented in '96) and it doesn't sound out of place IMO, so it's enabled by default (`snd_waterfx 0` disables it). Right now it also affects menu sounds, just like the underwater color shift affected the menu in the original software renderer. I might fix this in the future, but I'm not sure it's necessary.

**Comment by garoto** [comment]
Tested and it sounds literally pretty good! Good one!

**Comment by Hexaae** [comment]
Great! 🏆
