### ISSUE TITLE
Screenshot issue (F12 key). Saves with .pn extension instead of .png

### ISSUE THREAD

**Issue by Hexaae** [andrei-drexler/ironwail#48]
Just made a screenshot with F12 and noticed it saved a file named "ironwail0000.pn" instead of .png

**Comment by andrei-drexler** [comment]
Thanks, this has already been fixed (in https://github.com/andrei-drexler/ironwail/commit/f781fee90ac67ad91a3ff77413578193b55d6cc6). There will be a new release soon.
