### ISSUE TITLE
Mjolnir seam

### ISSUE THREAD

**Issue by Hexaae** [andrei-drexler/ironwail#51]
Not sure if it's an engine issue or the original 3d mesh of Quake is buggy but I noticed a ugly seam in the Mjolnir (demo4 of hipnotic 1st expansion pack):
![image](https://user-images.githubusercontent.com/8591462/155877233-ed1d1fb0-4f54-4ba4-ad29-afe307160dd6.png)

**Comment by andrei-drexler** [comment]
GLQuake (and all of its descendants, including QS/QSS/vkQuake) uses slightly different texture coordinates for models than the original software renderer - see https://github.com/Novum/vkQuake/issues/320. You can get the old behavior with the 'raw' 8-bit mode option.
