### ISSUE TITLE
[Bug] Client pitch angle is incorrectly restored on load game

### ISSUE THREAD

**Issue by mhQuake** [andrei-drexler/ironwail#53]
**Description**

Client pitch angle is incorrectly restored on load game. This bug is present in most Quake engines, and derives from the original ID software code. 

**Cause**

Host_Spawn_f sets viewangles from edict_t::v.angles, which is correct for first-time entry to a map and for general entities.  The actual player angles on the server are stored in edict_t::v.v_angle, however, so when restoring from a load game, the incorrect pitch angle (in particular) will be set: it will be 0.3 * the correct angle, but in the opposite direction.

**Steps to Reproduce**

- Start any map.
- Look down.
- Save the game while looking down.
- Load the game from this save file.
- You will be looking up at 0.3 of your angle.

**Suggested Fix**

In Host_Spawn_f, replace this block of code:

`	for (i = 0; i < 2; i++)`
`		MSG_WriteAngle (&host_client->message, ent->v.angles[i], sv.protocolflags );`

With this:

`	for (i = 0; i < 2; i++)`
`	{`
`		if (sv.loadgame)`
`			MSG_WriteAngle (&host_client->message, ent->v.v_angle[i], sv.protocolflags);`
`		else MSG_WriteAngle (&host_client->message, ent->v.angles[i], sv.protocolflags);`
`	}`

The new code correctly determines if the player is being spawned from a load game, and if so it writes the correct angle.

**Comment by andrei-drexler** [comment]
Thanks, applied in https://github.com/andrei-drexler/ironwail/commit/3d5dc57f81d7c66d31dce8689d4c0cf8ada81f8f.
