### ISSUE TITLE
r_skyfog is not capped

### ISSUE THREAD

**Issue by bstordeur** [andrei-drexler/ironwail#58]
In Ironwail, if you set r_skyfog over 1, the sky starts to reappear, whereas in other engines it caps at 1.

Example, skyfog at 2 : 
![image](https://user-images.githubusercontent.com/5883104/158082007-61d78ba0-005d-4f24-878f-965af39c0745.png)
vs in vkQ (where it looks the same at 1 and anything above that).
![image](https://user-images.githubusercontent.com/5883104/158082013-4c3f37ec-f847-43c7-ad9e-7c28720e7aa8.png)

This is on 0.4.0.

**Comment by andrei-drexler** [comment]
Thanks! Fixed in https://github.com/andrei-drexler/ironwail/commit/92245908bc0274c1bba288180b15b2097c234fcc.
