### ISSUE TITLE
Title Demo Music Doesn't play for Hipnotic when using -fitz mode

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#60]
Been doing some more playtesting when I noticed that loading Mission Pack 1 while using the `-fitz` parameter doesn't play the Scourge of Armagon theme upon loading the first demo, it actually just doesn't play any music at all.

**Comment by andrei-drexler** [comment]
Thanks! Fixed in https://github.com/andrei-drexler/ironwail/commit/0c1e2b256f516cf5f99c1975771dc38a5dc577e0.
