### ISSUE TITLE
Reported version is still 0.4.0

### ISSUE THREAD

**Issue by AAS** [andrei-drexler/ironwail#67]
At least on 0.5 x64 windows executable.
And binary build date is 2022-03-23.

**Comment by AAS** [comment]
Looks like I downloaded somehow outdated archive (in the same minute github emailed me about new version few days ago).
New archive is OK.

**Comment by andrei-drexler** [comment]
Thanks for reporting this, the 64-bit version initially uploaded was indeed outdated, I only replaced it 12 or so hours later. I've added a note at the top of the release info to avoid further confusion, and I'll also keep this issue open for a little longer, in case anyone else notices this.

**Comment by andrei-drexler** [comment]
Closing this issue - it's been 3 weeks, that should be enough.
