### ISSUE TITLE
Old Quit Messages?

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#69]
Would be nice to have the oldschool taunt messages when you try to quit the game. Could you perhaps add those back?

**Comment by andrei-drexler** [comment]
I never really liked those messages... but on the other hand, the current one is as dry as they come, so I've changed `cl_confirmquit` to show the old messages when set to `2` (bc8e2a4f0e61df35678d1bc4697164a2c2a89da2).
