### ISSUE TITLE
[Feature Request] Viewpos copies result to clipboard

### ISSUE THREAD

**Issue by Lain-tf** [andrei-drexler/ironwail#71]
Viewpos is usually used with Setpos / to apply the angles to entities in a map editor.  Right now this requires a lot of manual typing out, usually with a notepad window open. Copying it straight to the clipboard would heavily streamline the process.

**Comment by bstordeur** [comment]
Yeah I've dreamed of this for a long time, not sure why I never asked for it though.

**Comment by andrei-drexler** [comment]
This does sound like a useful feature, but I think the clipboard copy should be explicit since it overwrites existing contents which the user might care about. I've changed `viewpos` to accept an optional `copy` argument in ec5f1258f0adb89f62a0eca694687624016b8d05.
