### ISSUE TITLE
[Bug] Liquid textures shift between miplevels as they warp

### ISSUE THREAD

**Issue by mhQuake** [andrei-drexler/ironwail#75]
This is really subtle - you need to be viewing the texture from the correct distance, the correct angle, and it's also heavily dependent on your gl_texturemode setting, but it's one of those things that once you notice it for the first time...

The issue is that shader-based per-fragment warping generates slightly different gradients as it warps, which can cause parts of the texture to shift back and forth between different miplevels in time with the warp. 

The solution is to retrieve dFdx and dFdy from the unwarped texture coords, then do the texture lookup using the warped coords and textureGrad.

**Comment by andrei-drexler** [comment]
I don't really see why the mip level should stay constant with animating UVs, so I don't consider this a bug, just the GPU doing what it's supposed to. Not worth complicating the shaders and potentially degrading performance (due to increased traffic to the texture units) IMO for this.

**Comment by mhQuake** [comment]
That's fair enough if you don't want to do it, but I take issue with the claim about "complicating the shaders and potentially degrading performance" and can't let it pass. I wouldn't have offered the solution if I hadn't already written the code myself, multiple times over, and been aware of what it's performance and complexity was like.

**Comment by andrei-drexler** [comment]
That's just unlit water, though. Lit water, however, is implemented here as a variant of the main world shader, and that's where I wanted to avoid the extra complexity. As for the *potential* performance implications of `textureGrad`, there's some relevant info [here](https://twitter.com/bgolus/status/1377778470353215492). The cost might be minor, but after looking at screenshots with the current code and the proposed fix with different settings (aniso on/off, linear filtering on/off, render scale on/off), I didn't see any compelling reason for it.
