### ISSUE TITLE
[Feature request] OpenAL Soft 

### ISSUE THREAD

**Issue by markanini** [andrei-drexler/ironwail#76]
Any chance of implementing this? The Quakespasm audio capabilities are have some issues. 
1. Handling mixed sample rates is kind of clunky. You can configure it to downsample with quality loss(default), or upsample with heavy artifacting.
2. Makes 3D positional audio over headphones possible, which is a perfect fit for Quake. Here's an example if you want to see what it's about: https://www.youtube.com/watch?v=rc5a7dzRvbY

**Comment by andrei-drexler** [comment]
Unfortunately, I think that's a bit outside the scope of this project, I just don't have the energy to create/maintain another audio backend at the moment.

**Comment by markanini** [comment]
Fair enough. If I can make a smaller request, would you consider unrestricting higher-order audio filtering(snd_filteringquality) for sndspeed other than 11025? I believe the current behavior is for legacy reasons, it emulates the original exe, and should be kept for that reason. My proposition should make creators of custom sounds happy though, perhaps through a new cvar to cover different scenarios.
