### ISSUE TITLE
[Feature Request] r_showbboxes modification

### ISSUE THREAD

**Issue by KillPixelGames** [andrei-drexler/ironwail#77]
Requesting that the wireframe for bboxes are drawn in a color other than white (perhaps red-ish?) in order to be more easily visible when `r_showtris` is also enabled.

Also requesting an additional mode (2) where only bboxes of currently drawn entities are displayed.  The lack of bbox culling can make things quite busy and difficult to decipher.

**Comment by mhQuake** [comment]
Last time I did this I used a different colour for different entity types; so alias models might be 0xff8800, brush models 0x00ff88, bsp brush models 0x8800ff, etc.

**Comment by andrei-drexler** [comment]
Added `r_showbboxes 2` mode with PVS test in 0d8ed24cc145e03f29270e46966278e24a90f7f3 and colored display in 33f48a5ca8628d703773a832a59f23938d6fe2e2.
