### ISSUE TITLE
[Feature Request] r_softwarebanding equivalent 

### ISSUE THREAD

**Issue by KillPixelGames** [andrei-drexler/ironwail#78]
Requesting an `r_softwarebanding` equivalent.  This would be incredibly useful for projects that use custom palettes/white lighting, in addition to simply being a more accurate emulation of software rendering.

**Comment by andrei-drexler** [comment]
`r_softwarebanding` might be marginally more accurate when it works, but it doesn't support colored lighting (not without going off-palette), fog or transparency, which rules out most content made in recent years. Not a good tradeoff, IMO.

**Comment by KillPixelGames** [comment]
Ah, bummer! You're right this option wouldn't be useful for the majority of modern content, but it would be for id1/hipnotic/rogue, a ton of earlier content, and, in my case, non-quake projects.  That said, I don't know the technical challenges and time/effort required to implement something like this, as narrow in use as it is.
