### ISSUE TITLE
[Bug] r_softemu uses the designated fullbright ramps on non-fullbright colors in some instances

### ISSUE THREAD

**Issue by KillPixelGames** [andrei-drexler/ironwail#81]
Typically happens when surface is lit by both lightmaps and dynamic lights simultaneously (muzzle flashes, explosions, shambler attack, powerups, etc).

**Comment by andrei-drexler** [comment]
r_softemu palettization considers all 256 colors as possible candidates, supposedly the [same as the original colormap algorithm](https://quakewiki.org/wiki/Quake_palette#Generating_the_colormap), the main difference being that r_softemu uses a more perceptual color matching method in order to make better choices for colors in areas of the spectrum with poor coverage, even if this means that it sometimes produces slightly different output. Not a bug.

**Comment by mhQuake** [comment]
For reference, here's the original colormap algorithm: https://github.com/id-Software/Quake-Tools/blob/master/qutils/QLUMPY/QUAKEGRB.C#L203

(Reading the qutils code is highly recommended)

**Comment by andrei-drexler** [comment]
Thanks, it's definitely better to have an authoritative source on this rather than an educated guess.

**Comment by KillPixelGames** [comment]
> r_softemu palettization considers all 256 colors as possible candidates, supposedly the [same as the original colormap algorithm](https://quakewiki.org/wiki/Quake_palette#Generating_the_colormap), the main difference being that r_softemu uses a more perceptual color matching method in order to make better choices for colors in areas of the spectrum with poor coverage, even if this means that it sometimes produces slightly different output. Not a bug.

In my tests, the perceptual color matching is making poor choices in a number of cases to such an extent I wouldn't fault someone for mistaking it for a bug.

While developing a palette, I've been doing my best to work with this behavior.  However, even with those efforts and constant iteration, colors from different ramps are chosen even though many shades on the original ramp are still available and seem like a far closer match.

Could you give me some more insight on how colors are chosen?  With that knowledge I might be able to work with/round the current behavior and get satisfactory results.  If you'd like to take a closer look at this I'd be more than happy to provide any testing and information from my work.  If not, I'll just leave it be.
