### ISSUE TITLE
HUD Small Ammo Count Numbers Discolored in Latest Build

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#82]
Compiled and tested out the latest build today and noticed that the small ammo counters for each ammo type are using the wrong colors (brown instead of gold). Was this on purpose or is this a palettization issue?

**Comment by andrei-drexler** [comment]
Just an oversight while refactoring the code. Fixed in f3491e09a044800ab345b4839ea2b8303de61f7a.
