### ISSUE TITLE
[Feature Request] HUD style toggle in options menu

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#83]
Since you're adding some new minimal-style HUD options to the port, it would probably make sense to add a menu toggle to switch between the different options.

**Comment by OpenRift412** [comment]
**Alternatively,** You could integrate the `hudstyle` cvar as part of the viewsize cvar, where once the status bar is removed and has gone full-screen, increasing the viewsize further will toggle between the different full-screen HUD options, similar to how some Doom source ports do it.

**Comment by andrei-drexler** [comment]
The whole UI is in need of an overhaul, but until I figure out the best way to do that I agree that this is one of those options that really should be present in any case - afbd8c125a44c872d6e2d11c5cd12b7aa73182fb.
