### ISSUE TITLE
[BUG] Issue with how models are rendered in fog in "r_softemu 2"

### ISSUE THREAD

**Issue by theptoing** [andrei-drexler/ironwail#86]
![solid blobs in the fog](https://i.imgur.com/d48pPpS.png)

As you can see in this image there is a solid coloured silhouette of an enemy on the ground. I noticed this when playing around with fog values. In the Balanced software rendering setting models always are visible in the fog bc they do not get dithered accordingly.

**Comment by andrei-drexler** [comment]
Good catch, fixed in https://github.com/andrei-drexler/ironwail/commit/96b6078ad3ef326adafbc2b59828ed8c6c12a893.
