### ISSUE TITLE
[Bug] Hard-coded MAXALIASFRAMES bound can be exceeded by Protocols 666 or 999

### ISSUE THREAD

**Issue by mhQuake** [andrei-drexler/ironwail#88]
MAXALIASFRAMES is hard-coded to 256 and enforced by bounds-checking and a Sys_Error; protocols 666 and 999 allow up to 64k alias frames via U_FRAME2 bit, so these can exceed the 256 hard-coded limit.

**Comment by mhQuake** [comment]
Yes, for protocol compatibility the array would need to be extended and the runtime check would need to be modified to take account of the current protocol.

**Comment by andrei-drexler** [comment]
1024 frames ought to be enough for anybody.

-- Bill Gates probably
