### ISSUE TITLE
Feature Request: Having a proper official name for the fork

### ISSUE THREAD

**Issue by AtifArshad1995** [andrei-drexler/ironwail#9]
First of all, I would like to say thank you for creating this fork of QS. As someone with a low end laptop, I struggled playing some of the more detailed maps (like AD_Tears in Arcane Dimension etc.) at 60 fps. Your fork is the only one that runs such maps at 60+ fps for me. Keep up the great work :)

The feature request isn't really a request for a "feature" per se but a small suggestion to have a proper name for the fork to increase its popularity. I say this because this fork deserves more recognition for how much of performance it improved and it would be a shame if the port went under the radar of most players (and the more recognition means hopefully improving the chances of QS or QS-Spiked devs considering to add the optimization features this offers).

**Comment by andrei-drexler** [comment]
Struggling with low framerates in some spots on ad_tears is why I started looking into possible optimizations in the first place, so I'm glad to hear this fork made it easier to enjoy it - it's a fantastic map after all, and not just visually :)

As for a new name for this project - I've been meaning to come up with one for a while now to avoid confusion, but whenever I tried I just ended up with a lot of tabs open and no meaningful results. I'll keep trying, though, hopefully I'll have something for the next release.

PS - I should probably make this clear in the readme, but the changes in this fork practically amount to a full renderer rewrite that takes advantage of more modern(-ish) GPU features. Merging them back into QS/QSS would be somewhat complicated, especially since one of QS's major features is that it still works on very old hardware. The old code would have to live on side-by-side with the new one - not impossible, of course, but still quite a bit of work.

**Comment by dumptruckDS** [comment]
I'm waiting for the new name so I can do a proper video for my YT channel. :) https://www.youtube.com/c/dumptruckds

**Comment by andrei-drexler** [comment]
That's nice to hear (and the next release will be pretty hype-worthy, if I can say so myself), but I *still* haven't managed to come up with anything that really makes me think "yes, that's it"...

**Comment by andrei-drexler** [comment]
Thinking of going with 'Ironwail' since I've been playing mostly with host_maxfps 0... Not quite what I was looking for (a bit too edgy, would've preferred something sillier), but eh, I have to pick something eventually.

**Comment by garoto** [comment]
> Thinking of going with 'Ironwail' since I've been playing mostly with host_maxfps 0 [...]

Not sure what `Ironwail` can possibly mean coupled with `host_maxfps 0` for a native english speaker, assuming it means the computer hardware is "wailing" while rendering +666fps?

Anyways, I spent sometime persuing `curl --silent dict://dict.org/d:<keywords>:english` and this is the list I came up with, poorly sorted from my most liked to my less liked:

```
SpasmodicQuake
QuakeShakes
QuakeAche
QuakeAhead
QuakeBoom
KweikSpasm
QuakeThrill
QuakeCramps
QuakeBurst
QuakeOxide
QuakeBlast
UnrelentingQuake
QuakeFoundry
QuakeNouveau
QuakeNovo
QuakeNeo
QuakeFresh
QuakeVigor
QuakeThrill
QuakeJolt
FussQuake
```

**Comment by andrei-drexler** [comment]
"Ironwail" is just "coil whine, but make it sound medieval"

**Comment by garoto** [comment]
> "Ironwail" is just "coil whine, but make it sound medieval"

Holy shit, `coil whine` is actually a pretty good premisse.

**Comment by bstordeur** [comment]
I was ok with Ironwail, but now that I've heard it and said it a few times on voice-chat I think you should just go with IronWhale.

**Comment by GenericJohnDoeNO0** [comment]
quAKe47?
Quake'n'Shake?
BoyaQuake?
HMBQuake? (HoldMyBeerQuake)
G-Quake? (Gramps-Quake or Gravity Force Quake)
FFQuake? (FlipFingerQuake)
ICannaeQuake? (ICaQuake)
Quake4790k?
FunOptimizedQuake?(FOQu or FOQuake)

It seems i ate an clown this breakfeast, but some names sound good enough and would stick for a good performing engine with low hardware needs.

**Comment by mmillar-bolis** [comment]
FitzQuake started as a project to correct small, latent problems in GLQuake. QuakeSpasm took that further with rewritten music support, new protocols, etc. Finally this fork brings the engine _even further_, with a renewed focus on performance.

The engine went from fits to spasms. So what about calling your fork something like Qonvulsion?

**Comment by h4724** [comment]
If there's to be another name change it had better happen really soon, because Ironwail is already starting to stick.

**Comment by GenericJohnDoeNO0** [comment]
What is the status? Will we stick with Ironwail?

**Comment by andrei-drexler** [comment]
Yup, I think so. It's not quite what I had in mind, but it doesn't seem bad enough to change, either. Thanks for the suggestions, though, I do appreciate the help even if ultimately I'm not taking advantage of it.

**Comment by GenericJohnDoeNO0** [comment]
Anyway, Ironwail sounds cool enough for me.
