### ISSUE TITLE
[Feature Request] Support Model Scale

### ISSUE THREAD

**Issue by JosiahJack** [andrei-drexler/ironwail#90]
Add support for model scaling when entities have .float scale assigned in QC.  

This is necessary to not have floating models in maps that use scaled misc_models and to make some mods items look correct.  The protocol 999 should already support this.  I plan to look more into adding this here soon and PR'ing it.  I'm hoping this will be a simple add from how QSS handled it.

**Comment by JosiahJack** [comment]
Opened PR#110 for this https://github.com/andrei-drexler/ironwail/pull/110

**Comment by andrei-drexler** [comment]
Added via QS in 13c299080d32dc470ec91f4bd7711d684fdd9d88.
