### ISSUE TITLE
[feature] functional nomonsters cvar

### ISSUE THREAD

**Issue by theptoing** [andrei-drexler/ironwail#94]
There is a "nomonsters" cvar in Quake, but it seems like it never did anything. I think it would be nice to have to testing/debug reasons.
Maybe even a -nomonsters command line parameter which would be handy when building a map and starting it via necros compiler GUI.

**Comment by andrei-drexler** [comment]
This does seem like it could be useful, so I've added it in 91d630db72054414c90bc93d41f4e3e8bcfc36f8. It can break gameplay, though, so it comes with a warning. Saving is also disabled (to avoid creating broken saves), and the cvar is turned off automatically when loading a savefile.

No need for a new command-line parameter, btw, you can just start the game with `+nomonsters 1`.
