### ISSUE TITLE
[BUG] func _illusionary brushes disappearing

### ISSUE THREAD

**Issue by theptoing** [andrei-drexler/ironwail#95]
I just made a little test map to check out my Trenchbroom setup and got a weird bug where some func_illusionary brushes (the stuff with the teleporter textures) disappear from a certain vantage point. I placed the playerstart in such a way that they are invisible on map load, but will show up when you start looking around. I checked in Quakespasm, vkQuake and Ironwail. The bug only happens in IW.

[Here is a zip with the TB .map, the compiled bsp, as well as the texture wad I used.](https://mega.nz/file/6BlTUDbR#hyafM8VEpdWvMezCAS9JJshdw6cpZjRjM2oYWH6Dzi4)

I have no idea if this also happens with other entities, I did try func_wall however, which seemed to be fine. I also removed all but the first layer of teleporter wall,  same difference. It also does not seem to be because of the overlayed trigger volume.

**Comment by andrei-drexler** [comment]
Thanks, this has already been fixed as a side-effect of https://github.com/andrei-drexler/ironwail/commit/5eac03f46e8d3f22700f5530da6519bfd513798f.
