### ISSUE TITLE
Unable to launch/ "Error linking gui program"

### ISSUE THREAD

**Issue by rzhxiii** [andrei-drexler/ironwail#98]
Hi, I'm trying to run this on an unholy abomination of a laptop that should theoretically (at least I think so, not sure) be able to run it, but whenever I try to, I run into this error message.
![Capture](https://user-images.githubusercontent.com/82729328/175786641-55e803b8-4ca6-45ff-8f76-3d120fa44a10.PNG)
I've tried to delete all of my configs, but that didn't seem to make a difference.
I'm running **Windows 10 (32-bit)**.
My CPU is a 1.60 GHz i5-4200.
My GPU is an AMD Radeon HD 8670M (is it possible that Ironwail tries to use the integrated Intel graphics by default?).
Is this an issue with my hardware, with my drivers or something else?

**Comment by rzhxiii** [comment]
Yup, it was defaulting to the crappy Intel GPU.
Now I get a different error message with the AMD one:
![Capture](https://user-images.githubusercontent.com/82729328/175788245-4bec060e-d92a-4b10-96c5-553e0c1ec435.PNG)
Still, it seems that the issue is 100% GPU related. Please let me know if I should close this or keep it open until I can resolve it (in case you want additional information about this issue).

**Comment by tyfighter** [comment]
The first error seems likely to be related to the centroid storage qualifier.
`https://www.khronos.org/opengl/wiki/Shader_Compilation#Interface_matching`
> If GLSL 4.30 or later is available, then the [interpolation qualifiers](https://www.khronos.org/opengl/wiki/Interpolation_qualifiers) (including centroid and sample) do not need to match. Interpolation in GLSL 4.30 is determined solely by the qualifier specified by the [Fragment Shader](https://www.khronos.org/opengl/wiki/Fragment_Shader) (even if no qualifier is specified in the FS, which means the default will be used).
I guess the Intel iGPU driver needs centroid in both the vertex and fragment shader.

**Comment by rzhxiii** [comment]
Completely reinstalling the AMD drivers fixed the issue.

**Comment by andrei-drexler** [comment]
Great! I do have an AMD GPU from the same generation (GCN 1) somewhere in a drawer that I sometimes use to make sure the code still works there, but I'm glad I didn't have to swap it in. I've also added a work-around for the Intel driver bug (as pointed out by @tyfighter) in https://github.com/andrei-drexler/ironwail/commit/c2dad08e0e0b2d488d8303a0aa7d94d896578142. Actually hit a very similar bug a while ago on a different Intel iGPU (a4102818e78e319e332b8bba9361ccd756c5fd2e). Anyway, latest code/next release should work on the iGPU, too.
